"""``vetosh demo`` — zero-to-chat in one command.

Copies a small bundled corpus (a fictional company, Lumina Coffee Systems)
into a working directory, generates a DuckDB-backed config, and runs the
``vetosh up`` supervisor over it. The printed script walks the presenter
through the money shot: edit ``docs/pricing.md`` and watch the answer change.

Embedder/LLM selection (best available, no questions asked):

1. ``OPENAI_API_KEY`` set → OpenAI embeddings + OpenAI LLM (real answers);
2. ``sentence-transformers`` installed → local embeddings (real retrieval),
   mock LLM (the answer quotes the retrieved snippet);
3. otherwise → mock embedder + mock LLM, with a loud quality warning.
"""

from __future__ import annotations

import argparse
import importlib.util
import logging
import os
import shutil
import sys
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

_CORPUS_DIR = Path(__file__).parent / "corpus"

_SCRIPT = """
────────────────────────────────────────────────────────────────────────
 vetosh demo — Lumina Coffee Systems
 Chat UI:  http://localhost:{port}

 Try asking:
   • How much does the Team tier cost?
   • What happens if a machine goes offline?

 The live-sync moment:
   1. Open {docs_dir}/pricing.md
   2. Change the Team tier price (129 EUR → e.g. 199 EUR) and save
   3. Ask about the Team tier again — the answer follows the file
      (watch the “indexed … ago” counter in the header)

 Ctrl-C stops everything.
────────────────────────────────────────────────────────────────────────
"""


def choose_embedder() -> str:
    """Pick the best embedder available in this environment."""

    if os.environ.get("OPENAI_API_KEY"):
        return "openai"
    if importlib.util.find_spec("sentence_transformers") is not None:
        return "sentence_transformer"
    return "mock"


def build_demo_config(
    demo_dir: Path, *, port: int, embedder: str, license_key: str
) -> dict[str, Any]:
    """Assemble the demo config dict (pure; unit-tested)."""

    config: dict[str, Any] = {
        "pathway_license_key": license_key,
        "sources": [
            {"type": "fs", "path": str(demo_dir / "docs"), "glob": "**/*"}
        ],
        "vector_db": {
            "type": "duckdb",
            "path": str(demo_dir / "embeddings.duckdb"),
            "table": "demo_embeddings",
        },
        "persistence": {
            "enabled": True,
            "backend": "filesystem",
            "path": str(demo_dir / "persistence"),
        },
        "server": {"host": "127.0.0.1", "port": port},
    }
    if embedder == "openai":
        config["embedder"] = {"type": "openai", "api_key": "${OPENAI_API_KEY}"}
        config["llm"] = {"type": "openai", "api_key": "${OPENAI_API_KEY}"}
    elif embedder == "sentence_transformer":
        config["embedder"] = {"type": "sentence_transformer"}
        config["llm"] = {"type": "mock"}
    else:
        config["embedder"] = {"type": "mock"}
        config["llm"] = {"type": "mock"}
    return config


def _resolve_license_key() -> str:
    if os.environ.get("PATHWAY_LICENSE_KEY"):
        return "${PATHWAY_LICENSE_KEY}"
    print(
        "vetosh demo needs a (free) Pathway license key — one click at\n"
        "https://pathway.com/framework/get-license"
    )
    key = input("Paste your Pathway license key: ").strip()
    if not key:
        print("A license key is required.", file=sys.stderr)
        raise SystemExit(1)
    return key


def prepare_demo_dir(demo_dir: Path, *, port: int, license_key: str) -> Path:
    """Copy the corpus and write config.yaml; returns the config path."""

    docs = demo_dir / "docs"
    if not docs.exists():
        shutil.copytree(_CORPUS_DIR, docs)
    embedder = choose_embedder()
    if embedder == "mock":
        logger.warning(
            "Neither OPENAI_API_KEY nor sentence-transformers found: using the "
            "mock embedder (retrieval quality is NOT representative). "
            'Install "vetosh[local]" or set OPENAI_API_KEY for a real demo.'
        )
    elif embedder == "sentence_transformer":
        logger.info(
            "Using local sentence-transformers embeddings; /rag will quote "
            "retrieved snippets (set OPENAI_API_KEY for generated answers)."
        )
    config = build_demo_config(
        demo_dir, port=port, embedder=embedder, license_key=license_key
    )
    config_path = demo_dir / "config.yaml"
    config_path.write_text(
        "# generated by `vetosh demo`\n"
        + yaml.safe_dump(config, sort_keys=False, default_flow_style=False)
    )
    return config_path


def main(argv: list[str]) -> None:
    from vetosh.config.schema import load_config
    from vetosh.up import run as up_run

    parser = argparse.ArgumentParser(prog="vetosh demo", description=__doc__)
    parser.add_argument("--dir", default="./vetosh-demo", help="Demo working directory")
    parser.add_argument("--port", type=int, default=8000)
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    demo_dir = Path(args.dir).resolve()
    demo_dir.mkdir(parents=True, exist_ok=True)
    config_path = prepare_demo_dir(
        demo_dir, port=args.port, license_key=_resolve_license_key()
    )
    print(_SCRIPT.format(port=args.port, docs_dir=demo_dir / "docs"))
    sys.exit(up_run(load_config(config_path), str(config_path)))
